/**
 * Render the audit report as markdown (default) or JSON.
 *
 * Writes to --output path when supplied, otherwise to stdout.
 * Sets process.exitCode = 1 when any critical or high finding is present.
 *
 * JSON output schema
 * ------------------
 * {
 *   "version": "0.1.0",
 *   "date": "YYYY-MM-DD",
 *   "summary": { "critical": N, "high": N, "medium": N, "low": N, "total": N },
 *   "findings": [ ...Finding[] ]
 * }
 */
import { writeFileSync } from "node:fs";
import chalk from "chalk";
import { SEVERITY_ORDER, type Finding } from "./auditor.js";
import type { CliOptions, Severity } from "./index.js";

const VERSION = "0.1.0";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type Counts = Record<Severity, number>;

export function countBySeverity(findings: Finding[]): Counts {
  const c: Counts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of findings) c[f.severity]++;
  return c;
}

// ---------------------------------------------------------------------------
// JSON output
// ---------------------------------------------------------------------------

export interface AuditReport {
  version: string;
  date: string;
  summary: Counts & { total: number };
  findings: Finding[];
}

export function renderJson(findings: Finding[]): string {
  const counts = countBySeverity(findings);
  const report: AuditReport = {
    version: VERSION,
    date: new Date().toISOString().slice(0, 10),
    summary: { ...counts, total: findings.length },
    findings,
  };
  return JSON.stringify(report, null, 2);
}

// ---------------------------------------------------------------------------
// Markdown output (PRD §5 format)
// ---------------------------------------------------------------------------

const SEV_LABEL: Record<Severity, string> = {
  critical: "CRITICAL",
  high: "HIGH",
  medium: "MEDIUM",
  low: "LOW",
};

export function renderMarkdown(findings: Finding[]): string {
  const date = new Date().toISOString().slice(0, 10);
  const counts = countBySeverity(findings);
  const lines: string[] = [];

  lines.push(`# Anchor Audit Report`);
  lines.push(`Generated by anchor-audit v${VERSION} on ${date}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  for (const sev of ["critical", "high", "medium", "low"] as Severity[]) {
    lines.push(`| ${sev.charAt(0).toUpperCase() + sev.slice(1).padEnd(7)} | ${counts[sev]} |`);
  }
  lines.push(`| **Total** | **${findings.length}** |`);
  lines.push("");

  if (findings.length === 0) {
    lines.push(
      "> No findings. Always verify manually before deploying to mainnet."
    );
    return lines.join("\n");
  }

  lines.push("## Findings");
  lines.push("");

  // Group by severity for cleaner scanning
  const bySev = (["critical", "high", "medium", "low"] as Severity[]).flatMap(
    (s) => findings.filter((f) => f.severity === s)
  );

  for (const f of bySev) {
    const loc = f.line != null ? `${f.file}:${f.line}` : f.file;
    lines.push(`### [${SEV_LABEL[f.severity]}] Rule ${f.ruleId}: ${f.title}`);
    lines.push("");
    lines.push(`**File:** \`${loc}\``);
    lines.push("");
    lines.push(`**Description:** ${f.description}`);
    lines.push("");
    if (f.vulnerableCode.trim()) {
      lines.push("**Vulnerable code:**");
      lines.push("```rust");
      lines.push(f.vulnerableCode.trim());
      lines.push("```");
      lines.push("");
    }
    lines.push(`**Recommendation:** ${f.recommendation}`);
    lines.push("");
    lines.push(
      `**Reference:** [rules/${f.ruleId}-${f.ruleName}.md](rules/${f.ruleId}-${f.ruleName}.md)`
    );
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export async function renderReport(
  findings: Finding[],
  options: CliOptions
): Promise<void> {
  const output =
    options.format === "json" ? renderJson(findings) : renderMarkdown(findings);

  if (options.output) {
    writeFileSync(options.output, output, "utf8");
    const counts = countBySeverity(findings);
    const label =
      counts.critical > 0
        ? chalk.red(`${counts.critical} critical`)
        : counts.high > 0
          ? chalk.yellow(`${counts.high} high`)
          : chalk.green("clean");
    process.stderr.write(
      `Wrote report to ${options.output} — ${label}, ${findings.length} total finding(s)\n`
    );
  } else {
    process.stdout.write(output + "\n");
  }

  // Exit code 1 when any critical or high finding is present.
  const { critical, high } = countBySeverity(findings);
  if (critical > 0 || high > 0) {
    process.exitCode = 1;
  }
}

// Re-export SEVERITY_ORDER so tests can use it without importing from auditor
export { SEVERITY_ORDER };
