/**
 * Render the audit report as markdown (default) or JSON.
 *
 * Auto-save behaviour (always on):
 *   Every run writes a timestamped file to reports/<project>-<timestamp>.<ext>
 *   so no audit is ever lost.  Pass --output to additionally write to a
 *   specific path.  Stdout is printed when --output is not supplied.
 *
 * JSON output schema
 * ------------------
 * {
 *   "version": "0.1.0",
 *   "date": "YYYY-MM-DD",
 *   "metadata": { ...AuditMetadata },
 *   "summary": { "critical": N, "high": N, "medium": N, "low": N, "total": N },
 *   "findings": [ ...Finding[] ]
 * }
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import chalk from "chalk";
import { SEVERITY_ORDER, type Finding } from "./auditor.js";
import type { CliOptions, Severity } from "./index.js";
import type { AuditMetadata } from "./metadata.js";

const VERSION = "0.1.0";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

type Counts = Record<Severity, number>;

export function countBySeverity(findings: Finding[]): Counts {
  const c: Counts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const f of findings) c[f.severity]++;
  return c;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

// ---------------------------------------------------------------------------
// JSON output
// ---------------------------------------------------------------------------

export interface AuditReport {
  version: string;
  date: string;
  metadata?: AuditMetadata;
  summary: Counts & { total: number };
  findings: Finding[];
}

export function renderJson(findings: Finding[], meta?: AuditMetadata): string {
  const counts = countBySeverity(findings);
  const report: AuditReport = {
    version: VERSION,
    date: new Date().toISOString().slice(0, 10),
    ...(meta ? { metadata: meta } : {}),
    summary: { ...counts, total: findings.length },
    findings,
  };
  return JSON.stringify(report, null, 2);
}

// ---------------------------------------------------------------------------
// Markdown output
// ---------------------------------------------------------------------------

const SEV_LABEL: Record<Severity, string> = {
  critical: "CRITICAL",
  high: "HIGH",
  medium: "MEDIUM",
  low: "LOW",
};

function renderMetadataBlock(meta: AuditMetadata): string {
  const rows: [string, string][] = [
    ["Date", meta.date],
    ["Time", meta.time],
    ["Model", meta.model],
    ["Provider", meta.provider],
    ["Effort", meta.effort],
    ["CLI Version", `v${meta.cliVersion}`],
    ["Project", meta.project],
  ];
  if (meta.gitBranch) rows.push(["Git Branch", meta.gitBranch]);
  if (meta.gitCommit) rows.push(["Git Commit", meta.gitCommit]);
  rows.push(["OS", meta.os]);
  rows.push(["Duration", formatDuration(meta.durationMs)]);
  rows.push(["Files Analyzed", String(meta.totalFiles)]);
  rows.push(["Total Findings", String(meta.totalFindings)]);

  const lines = ["## Audit Metadata", "", "| Field | Value |", "|-------|-------|"];
  for (const [k, v] of rows) lines.push(`| ${k} | ${v} |`);
  return lines.join("\n");
}

export function renderMarkdown(findings: Finding[], meta?: AuditMetadata): string {
  const date = meta?.date ?? new Date().toISOString().slice(0, 10);
  const counts = countBySeverity(findings);
  const lines: string[] = [];

  lines.push(`# Anchor Audit Report`);
  lines.push(`Generated by anchor-audit v${VERSION} on ${date}`);
  lines.push("");

  if (meta) {
    lines.push(renderMetadataBlock(meta));
    lines.push("");
  }

  lines.push("## Summary");
  lines.push("");
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  for (const sev of ["critical", "high", "medium", "low"] as Severity[]) {
    lines.push(`| ${sev.charAt(0).toUpperCase() + sev.slice(1).padEnd(7)} | ${counts[sev]} |`);
  }
  lines.push(`| **Total** | **${findings.length}** |`);
  lines.push("");

  if (findings.length === 0) {
    lines.push(
      "> No findings. Always verify manually before deploying to mainnet."
    );
    return lines.join("\n");
  }

  lines.push("## Findings");
  lines.push("");

  const bySev = (["critical", "high", "medium", "low"] as Severity[]).flatMap(
    (s) => findings.filter((f) => f.severity === s)
  );

  for (const f of bySev) {
    const loc = f.line != null ? `${f.file}:${f.line}` : f.file;
    lines.push(`### [${SEV_LABEL[f.severity]}] Rule ${f.ruleId}: ${f.title}`);
    lines.push("");
    lines.push(`**File:** \`${loc}\``);
    lines.push("");
    lines.push(`**Description:** ${f.description}`);
    lines.push("");
    if (f.vulnerableCode.trim()) {
      lines.push("**Vulnerable code:**");
      lines.push("```rust");
      lines.push(f.vulnerableCode.trim());
      lines.push("```");
      lines.push("");
    }
    lines.push(`**Recommendation:** ${f.recommendation}`);
    lines.push("");
    lines.push(
      `**Reference:** [rules/${f.ruleId}-${f.ruleName}.md](rules/${f.ruleId}-${f.ruleName}.md)`
    );
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Auto-save to reports/
// ---------------------------------------------------------------------------

function autoSavePath(project: string, format: "markdown" | "json"): string {
  const ext = format === "json" ? "json" : "md";
  // Replace colons with dashes for filesystem-safe filenames.
  const ts = new Date().toISOString().replace(/:/g, "-").replace(/\..+$/, "Z");
  return join("reports", `${project}-${ts}.${ext}`);
}

function writeAutoSave(content: string, project: string, format: "markdown" | "json"): string {
  mkdirSync("reports", { recursive: true });
  const savePath = autoSavePath(project, format);
  writeFileSync(savePath, content, "utf8");
  return savePath;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export async function renderReport(
  findings: Finding[],
  options: CliOptions,
  meta?: AuditMetadata
): Promise<void> {
  const output =
    options.format === "json"
      ? renderJson(findings, meta)
      : renderMarkdown(findings, meta);

  const project = meta?.project ?? "audit";

  // Always auto-save a timestamped copy to reports/.
  const savedPath = writeAutoSave(output, project, options.format);

  if (options.output) {
    writeFileSync(options.output, output, "utf8");
  }

  const counts = countBySeverity(findings);
  const label =
    counts.critical > 0
      ? chalk.red(`${counts.critical} critical`)
      : counts.high > 0
        ? chalk.yellow(`${counts.high} high`)
        : chalk.green("clean");

  process.stderr.write(
    `Saved report → ${savedPath}` +
      (options.output ? ` (also → ${options.output})` : "") +
      ` — ${label}, ${findings.length} total finding(s)\n`
  );

  // Print to stdout when no --output flag (terminal viewing).
  if (!options.output) {
    process.stdout.write(output + "\n");
  }

  // Exit code 1 when any critical or high finding is present.
  if (counts.critical > 0 || counts.high > 0) {
    process.exitCode = 1;
  }
}

// Re-export SEVERITY_ORDER so tests can use it without importing from auditor
export { SEVERITY_ORDER };
